import type { Metadata } from "next";
import "./globals.css";

import Example from "@/app/Store-Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <Example/>
      {children}
      </body>
    </html>
  );
}
